// front-ends/react_login/app/pages/users/delete/deleteUser.tsx
import { toast } from "sonner";
import axios from "axios";
import { useNavigate } from "react-router";
import { useTranslation } from "react-i18next";

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "~/components/ui/alert-dialog";
import { Button } from "~/components/ui/button";
import { Trash2 } from "lucide-react";

import { API_URL} from "~/customConfig";

export function DeleteUser({id, email, usersChange}: {id: number; email: string; usersChange: () => void }) {
  const navigate = useNavigate();
  const { t } = useTranslation(); 

  const token = sessionStorage.getItem("token");

  function submit() {
    axios.delete(`${API_URL}/users/${id}`, {
      headers: {
        "Authorization": `Bearer ${token}`
      }
    })
    .then(() => {
      toast(t("users.delete.success.title"), {
        description: t("users.delete.success.desc")
      })

      usersChange();
    })
    .catch((error) => {
      // Display a toast whatever the error is to inform the user there has been an error and the user isn't deleted
      toast(t("users.delete.error.title"), {
        description: t("users.delete.error.desc")
      })

      if (error.status == 401) {
        navigate("/");
      } else {
        console.error(error);
      }
    })
  }

  return (
    <AlertDialog>
      <AlertDialogTrigger asChild>
        <Button variant="destructive">
          <Trash2 />
        </Button>
      </AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>{t("users.delete.title")} {email}</AlertDialogTitle>
          <AlertDialogDescription>{t("users.delete.desc")}</AlertDialogDescription>
        </AlertDialogHeader>
        
        <AlertDialogFooter>
          <AlertDialogCancel>{t("cancel")}</AlertDialogCancel>
          <AlertDialogAction onClick={submit}>{t("confirm")}</AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>

  )

}

// front-ends/vue_login/src/views/app_pages/Users/DeleteUser.vue
<script setup lang="ts">

import { API_URL } from '@/customConfig';

// ShadCn imports
import { Button } from '@/components/ui/button'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog';
import { useToast } from '@/components/ui/toast';

import axios from 'axios';

// Lucide imports
import { Trash2 } from 'lucide-vue-next';

import { useI18n } from 'vue-i18n'

const { t } = useI18n();
const { toast } = useToast();

const props = defineProps({
  id: Number
})
const emit = defineEmits(['user_change'])

const token = sessionStorage.getItem("token");

const deleteUser = () => {
    axios.delete(API_URL + `/users/${props.id}`, {
        headers: { Authorization: "Bearer " + token }
    })
    .then((response) => {
        toast({
            description: t("delete_user.success"),
        })
        emit('user_change');
    })
    .catch((error) => {
        toast({
            description: t("delete_user.error"),
        })
    })
}
</script>
<template>
    <AlertDialog>
        <AlertDialogTrigger>
            <Button variant="destructive">
                <Trash2 />
            </Button>
        </AlertDialogTrigger>
        <AlertDialogContent>
            <AlertDialogHeader>
                <AlertDialogTitle>{{ $t("delete_user.title") }}</AlertDialogTitle>
                <AlertDialogDescription>
                {{ $t("delete_user.description") }}
                </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
                <AlertDialogCancel>{{ $t("delete_user.cancel") }}</AlertDialogCancel>
                <div @click="deleteUser">
                    <AlertDialogAction>{{ $t("delete_user.confirm") }}</AlertDialogAction>
                </div>
            </AlertDialogFooter>
        </AlertDialogContent>
    </AlertDialog>
</template>
